
import React, { useState } from 'react';
import type { XmlResult } from '../types';

type Tab = 'metadata' | 'content';

const ActionButton: React.FC<{ icon: React.ReactNode; label: string; onClick: () => void; variant?: 'primary' | 'secondary' }> = ({ icon, label, onClick, variant = 'secondary' }) => (
  <button
    onClick={onClick}
    className={`flex items-center space-x-2 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
      variant === 'primary' 
      ? 'bg-emerald-600 hover:bg-emerald-500 text-white' 
      : 'bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700'
    }`}
  >
    {icon}
    <span>{label}</span>
  </button>
);

export const PreviewPane: React.FC<{ xmlResult: XmlResult }> = React.memo(({ xmlResult }) => {
  const [activeTab, setActiveTab] = useState<Tab>('metadata');
  const [copied, setCopied] = useState(false);

  const activeContent = activeTab === 'metadata' ? xmlResult.metadata : xmlResult.content;
  const activeFilename = activeTab === 'metadata' ? xmlResult.metadataFilename : xmlResult.contentFilename;

  const handleDownload = () => {
    const blob = new Blob([activeContent], { type: 'application/xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = activeFilename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(activeContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex flex-col h-full bg-slate-900/50">
      <div className="p-4 border-b border-slate-800 flex items-center justify-between bg-slate-900">
        <div className="flex p-1 bg-slate-950 rounded-xl space-x-1 border border-slate-800">
          <button 
            onClick={() => setActiveTab('metadata')}
            className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${activeTab === 'metadata' ? 'bg-emerald-600 text-white shadow-lg shadow-emerald-900/20' : 'text-slate-500 hover:text-slate-300'}`}
          >
            METADATA XML
          </button>
          <button 
            onClick={() => setActiveTab('content')}
            className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${activeTab === 'content' ? 'bg-emerald-600 text-white shadow-lg shadow-emerald-900/20' : 'text-slate-500 hover:text-slate-300'}`}
          >
            CONTENT XML
          </button>
        </div>

        <div className="flex space-x-2">
          <ActionButton 
            onClick={handleCopy}
            label={copied ? "Copied!" : "Copy"}
            icon={<svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"/></svg>}
          />
          <ActionButton 
            variant="primary"
            onClick={handleDownload}
            label="Download XML"
            icon={<svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a2 2 0 002 2h12a2 2 0 002-2v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/></svg>}
          />
        </div>
      </div>

      <div className="flex-grow p-6 overflow-auto font-mono text-xs leading-relaxed custom-scrollbar">
        <div className="bg-slate-950 p-6 rounded-2xl border border-slate-800 shadow-inner">
          <pre className="text-emerald-400 whitespace-pre-wrap selection:bg-emerald-500/20">
            <code>{activeContent}</code>
          </pre>
        </div>
      </div>

      <div className="p-3 bg-slate-900 border-t border-slate-800 flex items-center justify-between text-[10px] text-slate-500 font-mono italic">
        <span>Generated by LegalXML Engine v2.0</span>
        <span>Target: {activeFilename}</span>
      </div>
    </div>
  );
});
